In [1]:
import numpy as np
from scipy import stats 

In [3]:
mean = 30
std = 16
size = 10
np.random.normal(mean, std, size)

array([38.03151702, 32.86143966, 52.20779134, 49.83660137, 26.29318692,
       17.03402576, 30.8705163 , 16.69677814, 16.73207697, 22.64641032])

In [5]:
stats.norm.cdf(40, mean,std)

0.7340144709512995

In [6]:
stats.norm.rvs(loc=mean, scale=std, size=5)

array([ 16.48120727,  33.66984559,   5.84053041,  -0.70857499,
       -10.86150678])

In [7]:
np.random.normal(loc=mean, scale=std, size=5)

array([-12.95544548,  28.6835972 ,  46.98210269,  38.09146747,
        28.7924969 ])